export const ActionTypes = {
  // GET_MOVIES_REQUESTED: "GET_MOVIES_REQUESTED",
  // GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  // GET_MOVIES_ERROR: "GET_MOVIES_ERROR",

  GET_RANDOM_REQUESTED: "GET_RANDOM_REQUESTED",
  GET_RANDOM_SUCCESS: "GET_RANDOM_SUCCESS",
  GET_RANDOM_ERROR: "GET_RANDOM_ERROR",

  // SEARCH_VALIU: "SEARCH_VALIU",
  // SELECTED_MOVIE: "SELECTED_MOVIE",
};
